server:
  port: 4444

spring:
  application:
    name: elk

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: test
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    template:
      default-topic: test-elk
  
  datasource:
    url: jdbc:postgresql://localhost:5432/datalake_elk
    username: postgres
    password: admin
  
  elasticsearch:
    host: localhost
    port: 9200
    index: test_elk
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
