# server:
#   port: 4444

spring:
  application:
    name: elk

  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: test
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    template:
      default-topic: test-elk
